# Generated by Django 6.0.5 on 2026-05-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('anio_lanzamiento', models.IntegerField()),
                ('portada_url', models.CharField(max_length=300)),
                ('spotify_url', models.CharField(max_length=300)),
            ],
        ),
    ]
